# ---------------------------------------------------------------------------
# fornext.py
# Created on: 2011-11-18 11:13:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# \
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
  
# set workspace environment
out_path = "C:/arc/work/"

env.workspace = out_path

good_bad_reclassified = "C:/arc/good_bad_reclassified.shp"
cph_osm_points = "C:/arc/CPH_OSM_Points.shp"

good_bad_reclassified_rows = arcpy.SearchCursor(good_bad_reclassified)

for good_bad_reclassified_row in good_bad_reclassified_rows:
    
    NEAR_FID = good_bad_reclassified_row.getValue("NEAR_FID")
    text = good_bad_reclassified_row.getValue("text")
    type = good_bad_reclassified_row.getValue("type")
    dropdown = good_bad_reclassified_row.getValue("dropdown")
    rspdid = good_bad_reclassified_row.getValue("rspdid")
    t_nmbr = good_bad_reclassified_row.getValue("t_nmbr")
    reclass = good_bad_reclassified_row.getValue("reclass")
    
    cph_osm_points_rows = arcpy.UpdateCursor(cph_osm_points, "FID=" + str(NEAR_FID),"","","")
    
    for cph_osm_points_row in cph_osm_points_rows:
        cph_osm_points_row.exp_point = 1
        
        cph_osm_points_row.text = text
        cph_osm_points_row.type = type
        cph_osm_points_row.rspdid = rspdid
        cph_osm_points_row.dropdown = dropdown
        cph_osm_points_row.reclass = reclass
        
        
        
        cph_osm_points_rows.updateRow(cph_osm_points_row)
        print type + " - " + dropdown
        
        del cph_osm_points_row
        
    del cph_osm_points_rows
        
print "finished."
        
    